### ISSUE TITLE
#US11: "COMO equipo DesarrollAR QUIERO convertir los archivos.html en una SPA en Angular (módulos y componentes) PARA migrar el proyecto en dicho Framework." #TK11: Crear módulos y componentes en Angular

### ISSUE THREAD

**Issue by TrianaDevia** [TrianaDevia/Game-Mate-Modulo-Programador-Web-2023#43]

**Comment by TrianaDevia** [comment]
Equipo considero los siguientes componentes:
LAYOUTS
header
footer
PAGES
index
registro
login
producto
tienda
contacto
terminos y condiciones
Por favor, evalúen si esta correcto así nos ponemos a trabajar cuanto antes. Gracias

**Comment by EduRePiN** [comment]
Ya esta creado el proyecto en angular, se integro bootstrap y se creo el primer componente header.

**Comment by TrianaDevia** [comment]
Creo componente footer.

**Comment by TrianaDevia** [comment]
Creacion del proyecto inicial, bootstrap y rutas: Eduardo
Estructuración 
**pages** 
index: Triana
nosotros: Andrea
contacto: Marcelo
productos: Jesi
tienda: Jesi
términos y condiciones: Mati
**shared**
header: Triana
footer: Triana
**auth**
login: Debi
registro: Debi
**servicios** (crear a futuro este modulo para hacer la conexión con el backend) 
_Esta todo el equipo de acuerdo?_
